### ISSUE TITLE
Why Elastijk and not official API ?

### ISSUE THREAD

**Issue by duylong** [reyjrar/es-utils#20]
Hi,

I have a question about the API Elasticsearch. Why did you have taken "Elastijk" and not "Search::Elasticsearch", the official Elasticsearch API ?

Best regards,

**Comment by reyjrar** [comment]
Well, I've been developing this module for a few years, long before Search::Elasticsearch existed.

There are two main reasons:

1. Before it was Search::Elasticsearch it was "ElasticSearch" and I was using it, until Elastic.co uploaded the new version of as "Elasticsearch" and broke the CPAN.  I *was* using Elasticsearch.pm in these utilities (the historic, but at the time official API from Elastic.co, then Elasticsearch.com).  When they broke the CPAN (due to CPAN supporting case-insensitive file systems and the difference in "ElasticSearch" and "Elasticsearch"), I abandoned their code for Elastijk to push a version to the CPAN that people could actually install.

2. Elastijk was built to be as fast as possible when interacting with an HTTP webservice.  It makes certain assumptions that other HTTP libraries don't make for compatibility/flexibility.  I wanted these utilities to be as fast as possible.

I like Elastijk for it's simplicity and speed.  There is no reason to convert the code base to Search::Elasticsearch.  I even have App::ElasticSearch::Utilities::VersionHacks which provides wrappers to safely run your code and my code regardless of the version of Elasticsearch you or I run on our clusters.  With subtle API changes, I've had to update this module several times and don't think I could provide a consistent, reliable interface to ES in the same way via Search::Elasticsearch.

Since making the switch, no changes pushed by Hijk or Elastijk have caused any incompatibilities or test failures for me or my users.  That is *REALLY* important.
